/*
 * Stepper_Motor.c
 *
 * Created: 7/17/2023 5:16:03 PM
 *  Author: karim
 */ 
#include "Stepper_Motor_Interface.h"

void Stepper_Motor_Init() 
{
	DIO_Write_Pin_Dir(STEPPER_MOTOR_PORT0,STEPPER_MOTOR_PIN0,OUT) ; 
	DIO_Write_Pin_Dir(STEPPER_MOTOR_PORT1,STEPPER_MOTOR_PIN1,OUT) ;
	DIO_Write_Pin_Dir(STEPPER_MOTOR_PORT2,STEPPER_MOTOR_PIN2,OUT) ;
	DIO_Write_Pin_Dir(STEPPER_MOTOR_PORT3,STEPPER_MOTOR_PIN3,OUT) ;
	
	#if STEPPER_MOTOR_MODE == STEPPER_MOTOR_FULL_STEP	
	
	DIO_Write_Pin(STEPPER_MOTOR_PORT0,STEPPER_MOTOR_PIN0, HIGH);
	_delay_ms(100);
	DIO_Write_Pin(STEPPER_MOTOR_PORT0,STEPPER_MOTOR_PIN0, LOW);
	
	DIO_Write_Pin(STEPPER_MOTOR_PORT1,STEPPER_MOTOR_PIN1, HIGH);
	_delay_ms(100);
	DIO_Write_Pin(STEPPER_MOTOR_PORT1,STEPPER_MOTOR_PIN1, LOW);
	
	DIO_Write_Pin(STEPPER_MOTOR_PORT2,STEPPER_MOTOR_PIN2, HIGH);
	_delay_ms(100);
	DIO_Write_Pin(STEPPER_MOTOR_PORT2,STEPPER_MOTOR_PIN2, LOW);

	DIO_Write_Pin(STEPPER_MOTOR_PORT3,STEPPER_MOTOR_PIN3, HIGH);
	_delay_ms(100);
	DIO_Write_Pin(STEPPER_MOTOR_PORT3,STEPPER_MOTOR_PIN3, LOW);
	
	#elif STEPPER_MOTOR_MODE == STEPPER_MOTOR_HALF_STEP
	
	DIO_Write_Pin(STEPPER_MOTOR_PORT0,STEPPER_MOTOR_PIN0, HIGH); // 0001
	_delay_ms(100);
	DIO_Write_Pin(STEPPER_MOTOR_PORT1,STEPPER_MOTOR_PIN1, HIGH); // 0011
	_delay_ms(100);
	DIO_Write_Pin(STEPPER_MOTOR_PORT0,STEPPER_MOTOR_PIN0, LOW);  // 0010
	_delay_ms(100);
	DIO_Write_Pin(STEPPER_MOTOR_PORT2,STEPPER_MOTOR_PIN2, HIGH); // 0110
	_delay_ms(100);
	DIO_Write_Pin(STEPPER_MOTOR_PORT1,STEPPER_MOTOR_PIN1, LOW);  // 0100
	_delay_ms(100);
	DIO_Write_Pin(STEPPER_MOTOR_PORT3,STEPPER_MOTOR_PIN3, HIGH); // 1100
	_delay_ms(100);
	DIO_Write_Pin(STEPPER_MOTOR_PORT2,STEPPER_MOTOR_PIN2, LOW);  // 1000
	_delay_ms(100);
	DIO_Write_Pin(STEPPER_MOTOR_PORT0,STEPPER_MOTOR_PIN0, HIGH); // 1001
	_delay_ms(100);
	DIO_Write_Pin(STEPPER_MOTOR_PORT3,STEPPER_MOTOR_PIN3, LOW);  // 0001

#endif
}

void Stepper_Motor_GoForward() 
{
	// Turn One Side CCW
	for (int j=0; j<48; j++)
	{
		DIO_Write_Pin( STEPPER_MOTOR_PORT0 , STEPPER_MOTOR_PIN0   , LOW   ) ;
		DIO_Write_Pin( STEPPER_MOTOR_PORT1 , STEPPER_MOTOR_PIN1   , HIGH  ) ;
		DIO_Write_Pin( STEPPER_MOTOR_PORT2 , STEPPER_MOTOR_PIN2 , HIGH  ) ;
		DIO_Write_Pin( STEPPER_MOTOR_PORT3 , STEPPER_MOTOR_PIN3 , HIGH  ) ;

		_delay_ms( 2 ) ;

		DIO_Write_Pin( STEPPER_MOTOR_PORT0 , STEPPER_MOTOR_PIN0   , HIGH  ) ;
		DIO_Write_Pin( STEPPER_MOTOR_PORT1 , STEPPER_MOTOR_PIN1   , LOW   ) ;
		DIO_Write_Pin( STEPPER_MOTOR_PORT2 , STEPPER_MOTOR_PIN2 , HIGH  ) ;
		DIO_Write_Pin( STEPPER_MOTOR_PORT3 , STEPPER_MOTOR_PIN3 , HIGH  ) ;

		_delay_ms( 2 ) ;

		DIO_Write_Pin( STEPPER_MOTOR_PORT0 , STEPPER_MOTOR_PIN0   , HIGH  ) ;
		DIO_Write_Pin( STEPPER_MOTOR_PORT1 , STEPPER_MOTOR_PIN1   , HIGH  ) ;
		DIO_Write_Pin( STEPPER_MOTOR_PORT2 , STEPPER_MOTOR_PIN2 , LOW   ) ;
		DIO_Write_Pin( STEPPER_MOTOR_PORT3 , STEPPER_MOTOR_PIN3 , HIGH  ) ;

		_delay_ms( 2 ) ;

		DIO_Write_Pin( STEPPER_MOTOR_PORT0 , STEPPER_MOTOR_PIN0   , HIGH  ) ;
		DIO_Write_Pin( STEPPER_MOTOR_PORT1 , STEPPER_MOTOR_PIN1   , HIGH  ) ;
		DIO_Write_Pin( STEPPER_MOTOR_PORT2 , STEPPER_MOTOR_PIN2 , HIGH  ) ;
		DIO_Write_Pin( STEPPER_MOTOR_PORT3 , STEPPER_MOTOR_PIN3 , LOW   ) ;

		_delay_ms( 2 ) ;
	}
}
void Stepper_Motor_GoBackward() 
{
	// Turn The Other Side CCW
	for (int j=0 ; j<48 ; j++)
	{
		DIO_Write_Pin( STEPPER_MOTOR_PORT0 , STEPPER_MOTOR_PIN0   , HIGH   ) ;
		DIO_Write_Pin( STEPPER_MOTOR_PORT1 , STEPPER_MOTOR_PIN1   , HIGH  ) ;
		DIO_Write_Pin( STEPPER_MOTOR_PORT2 , STEPPER_MOTOR_PIN2 , HIGH  ) ;
		DIO_Write_Pin( STEPPER_MOTOR_PORT3 , STEPPER_MOTOR_PIN3 , LOW  ) ;

		_delay_ms( 2 ) ;

		DIO_Write_Pin( STEPPER_MOTOR_PORT0 , STEPPER_MOTOR_PIN0   , HIGH  ) ;
		DIO_Write_Pin( STEPPER_MOTOR_PORT1 , STEPPER_MOTOR_PIN1   , HIGH   ) ;
		DIO_Write_Pin( STEPPER_MOTOR_PORT2 , STEPPER_MOTOR_PIN2 , LOW  ) ;
		DIO_Write_Pin( STEPPER_MOTOR_PORT3 , STEPPER_MOTOR_PIN3 , HIGH  ) ;

		_delay_ms( 2 ) ;

		DIO_Write_Pin( STEPPER_MOTOR_PORT0 , STEPPER_MOTOR_PIN0   , HIGH  ) ;
		DIO_Write_Pin( STEPPER_MOTOR_PORT1 , STEPPER_MOTOR_PIN1   , LOW  ) ;
		DIO_Write_Pin( STEPPER_MOTOR_PORT2 , STEPPER_MOTOR_PIN2 , HIGH   ) ;
		DIO_Write_Pin( STEPPER_MOTOR_PORT3 , STEPPER_MOTOR_PIN3 , HIGH  ) ;

		_delay_ms( 2 ) ;

		DIO_Write_Pin( STEPPER_MOTOR_PORT0 , STEPPER_MOTOR_PIN0   , LOW  ) ;
		DIO_Write_Pin( STEPPER_MOTOR_PORT1 , STEPPER_MOTOR_PIN1   , HIGH  ) ;
		DIO_Write_Pin( STEPPER_MOTOR_PORT2 , STEPPER_MOTOR_PIN2 , HIGH  ) ;
		DIO_Write_Pin( STEPPER_MOTOR_PORT3 , STEPPER_MOTOR_PIN3 , HIGH   ) ;

		_delay_ms( 2 ) ;
	}
}
void Stepper_Motor_TurnOff() 
{
	DIO_Write_Pin( STEPPER_MOTOR_PORT0,STEPPER_MOTOR_PIN0 , HIGH  ) ;
	DIO_Write_Pin(STEPPER_MOTOR_PORT0,STEPPER_MOTOR_PIN0 , HIGH  ) ;
	DIO_Write_Pin( STEPPER_MOTOR_PORT0,STEPPER_MOTOR_PIN0, HIGH  ) ;
	DIO_Write_Pin( STEPPER_MOTOR_PORT0,STEPPER_MOTOR_PIN0, HIGH   ) ;
}